### ISSUE TITLE
Routing Errors should be logged differently

### ISSUE THREAD

**Issue by philayres** [consected/restructure#25]
For example, a common routing error causes a full stack trace to be recorded in the log file

```text
F, [2023-01-09T09:22:04.400166 #27711] FATAL -- :   
F, [2023-01-09T09:22:04.400234 #27711] FATAL -- : ActionController::RoutingError (No route matches [GET] "/autodiscover/autodiscover.json"):
F, [2023-01-09T09:22:04.400251 #27711] FATAL -- :   
F, [2023-01-09T09:22:04.400273 #27711] FATAL -- : vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
vendor/bundle/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/rack/logger.rb:38:in `call_app'
vendor/bundle/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/rack/logger.rb:26:in `block in call'
vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/tagged_logging.rb:28:in `tagged'
vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/tagged_logging.rb:71:in `tagged'
vendor/bundle/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/rack/logger.rb:26:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.5/lib/rack/method_override.rb:24:in `call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.5/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/static.rb:127:in `call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.5/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/ssl.rb:74:in `call'
vendor/bundle/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/engine.rb:524:in `call'
vendor/bundle/ruby/2.7.0/gems/puma-6.0.2/lib/puma/configuration.rb:268:in `call'
vendor/bundle/ruby/2.7.0/gems/puma-6.0.2/lib/puma/request.rb:93:in `block in handle_request'
vendor/bundle/ruby/2.7.0/gems/puma-6.0.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
```

The desired approach is just to record a simple WARN line without stacktrace.

**Comment by philayres** [comment]
Added in 8c2603ab1dde3d251235f13580505d9eba5b1dbe
